In [1]:
#numpy function practise

In [2]:
import numpy as np

In [3]:
# 1. Creating a NumPy array using np.array()
arr = np.array([10, 20, 30, 40, 50])
print("np.array ->", arr)

np.array -> [10 20 30 40 50]


In [4]:
# 2. Identity matrix with np.eye()
eye_mat = np.eye(3)  # generates a 3x3 identity matrix
print("\nnp.eye ->\n", eye_mat)


np.eye ->
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# 3. Evenly spaced values with np.linspace()
lin_vals = np.linspace(1, 5, 9)  # 9 values between 1 and 5
print("\nnp.linspace ->", lin_vals)


np.linspace -> [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [6]:
# 4. Sequential numbers with np.arange()
arange_vals = np.arange(2, 15, 3)  # numbers from 2 to 15 with step size 3
print("\nnp.arange ->", arange_vals)


np.arange -> [ 2  5  8 11 14]


In [7]:
# 5. Array of zeros using np.zeros()
zero_matrix = np.zeros((2, 6))  # 2 rows, 6 columns filled with 0
print("\nnp.zeros ->\n", zero_matrix)


np.zeros ->
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
# 6. Array of ones using np.ones()
ones_matrix = np.ones((4, 2))  # 4 rows, 2 columns filled with 1
print("\nnp.ones ->\n", ones_matrix)



np.ones ->
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# 7. Constant value array using np.full()
const_array = np.full((3, 5), 9)  # 3x5 array with all elements = 9
print("\nnp.full ->\n", const_array)


np.full ->
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [10]:
# 8. Random floats between 0 and 1 using np.random.rand()
random_floats = np.random.rand(3, 2)
print("\nnp.random.rand ->\n", random_floats)


np.random.rand ->
 [[0.1061553  0.90251429]
 [0.48455247 0.90008912]
 [0.26650897 0.70926879]]


In [11]:
# 9. Random integers with np.random.randint()
random_ints = np.random.randint(5, 50, size=(2, 4))
print("\nnp.random.randint ->\n", random_ints)



np.random.randint ->
 [[18 43 26  9]
 [45 25 48 12]]


In [12]:
# 10. Creating index grids with np.indices()
grid_idx = np.indices((2, 3))
print("\nnp.indices ->\n", grid_idx)


np.indices ->
 [[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


In [13]:
# 11. Array properties
print("\nArray Properties:")
print("Dimensions (ndim):", arr.ndim)
print("Number of elements (size):", arr.size)
print("Shape (rows, cols):", arr.shape)


Array Properties:
Dimensions (ndim): 1
Number of elements (size): 5
Shape (rows, cols): (5,)


In [14]:
# 12. Reshaping with np.reshape()
reshaped_arr = np.arange(16).reshape(4, 4)
print("\nnp.reshape ->\n", reshaped_arr)


np.reshape ->
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
# 13. Transpose of matrix using .T
transposed_arr = reshaped_arr.T
print("\nTranspose ->\n", transposed_arr)


Transpose ->
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [16]:
# 14. Basic mathematical operations
nums = np.array([2, 4, 6, 8, 10])
print("\nMath operations:")
print("Sum:", np.sum(nums))
print("Average:", np.mean(nums))
print("Maximum:", np.max(nums))
print("Minimum:", np.min(nums))
print("Std Deviation:", np.std(nums))



Math operations:
Sum: 30
Average: 6.0
Maximum: 10
Minimum: 2
Std Deviation: 2.8284271247461903


In [17]:
# 15. Creating a diagonal matrix with np.diag()
diag_matrix = np.diag([4, 8, 12])
print("\nnp.diag ->\n", diag_matrix)


np.diag ->
 [[ 4  0  0]
 [ 0  8  0]
 [ 0  0 12]]


In [18]:
# 16. Flattening array using np.ravel()
flat_arr = reshaped_arr.ravel()
print("\nnp.ravel ->", flat_arr)


np.ravel -> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [19]:
# 17. Sorting arrays with np.sort()
unsorted = np.array([12, 4, 9, 1, 7])
sorted_output = np.sort(unsorted)
print("\nnp.sort ->", sorted_output)


np.sort -> [ 1  4  7  9 12]


In [20]:
# 18. Unique values with np.unique()
dup_array = np.array([1, 2, 2, 3, 4, 3, 1, 5])
unique_output = np.unique(dup_array)
print("\nnp.unique ->", unique_output)


np.unique -> [1 2 3 4 5]


In [21]:
# 19. Concatenating arrays using np.concatenate()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged = np.concatenate((arr1, arr2))
print("\nnp.concatenate ->", merged)


np.concatenate -> [1 2 3 4 5 6]


In [22]:
# 20. Splitting arrays with np.split()
splits = np.split(np.arange(10), 5)
print("\nnp.split ->", splits)


np.split -> [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [23]:
# 21. Vertical stacking with np.vstack()
v_stacked = np.vstack((arr1, arr2))
print("\nnp.vstack ->\n", v_stacked)



np.vstack ->
 [[1 2 3]
 [4 5 6]]


In [24]:
# 22. Horizontal stacking with np.hstack()
h_stacked = np.hstack((arr1, arr2))
print("\nnp.hstack ->", h_stacked)


np.hstack -> [1 2 3 4 5 6]


In [25]:
# 23. Conditional extraction with np.where()
cond_arr = np.array([5, 10, 15, 20, 25])
indices = np.where(cond_arr > 12)  # find indices where value > 12
print("\nnp.where ->", indices)


np.where -> (array([2, 3, 4]),)


In [26]:
# 24. Clipping values with np.clip()
clip_arr = np.array([3, 15, 7, 22, 1])
clipped = np.clip(clip_arr, 5, 15)  # keep values within [5, 15]
print("\nnp.clip ->", clipped)


np.clip -> [ 5 15  7 15  5]


In [30]:
# 25. Dot product with np.dot()
dot_a = np.array([[1, 2], [3, 4]])
dot_b = np.array([[2, 0], [1, 2]])
dot_result = np.dot(dot_a, dot_b)
print("\nnp.dot ->\n", dot_result)


np.dot ->
 [[ 4  4]
 [10  8]]


In [31]:
# 26. Cumulative sum with np.cumsum()
cum_sum = np.cumsum([1, 2, 3, 4, 5])
print("\nnp.cumsum ->", cum_sum)


np.cumsum -> [ 1  3  6 10 15]


In [32]:
# 27. Cumulative product with np.cumprod()
cum_prod = np.cumprod([1, 2, 3, 4])
print("\nnp.cumprod ->", cum_prod)


np.cumprod -> [ 1  2  6 24]


In [33]:
# 28. Generating evenly spaced numbers in log scale with np.logspace()
log_vals = np.logspace(1, 3, 5)  # from 10^1 to 10^3 with 5 values
print("\nnp.logspace ->", log_vals)


np.logspace -> [  10.           31.6227766   100.          316.22776602 1000.        ]


In [34]:
# 29. Checking NaN values with np.isnan()
nan_arr = np.array([1, 2, np.nan, 4])
print("\nnp.isnan ->", np.isnan(nan_arr))


np.isnan -> [False False  True False]


In [35]:
# 30. Boolean masking with conditions
mask_arr = np.array([10, 15, 20, 25, 30])
masked = mask_arr[mask_arr > 18]  # only values > 18
print("\nBoolean Masking ->", masked)


Boolean Masking -> [20 25 30]
